# Generated by Django 5.1.5 on 2025-02-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_routes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannedWord',
        ),
    ]
