# Generated by Django 5.1.5 on 2025-02-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_routes', '0002_delete_bannedword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
