# Generated by Django 5.1.5 on 2025-03-01 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_routes', '0003_alter_photo_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='routes/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='travel_routes.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
