# Generated by Django 5.1.5 on 2025-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='photo',
            field=models.ImageField(upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
